# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Alloc_RNA_config = debug

else ifeq ($(config),release)
  Alloc_RNA_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Alloc_RNA

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Alloc_RNA:
ifneq (,$(Alloc_RNA_config))
	@echo "==== Building Alloc_RNA ($(Alloc_RNA_config)) ===="
	@${MAKE} --no-print-directory -C Alloc_RNA -f Makefile config=$(Alloc_RNA_config)
endif

clean:
	@${MAKE} --no-print-directory -C Alloc_RNA -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Alloc_RNA"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"